// Generated by CoffeeScript 1.6.3
(function() {
  var file_load, removable_loader;

  file_load = require('./lib/file_load');

  removable_loader = module.exports.load = function(config_files, callback) {
    var arg, next, _i, _len, _ref;
    if (config_files == null) {
      config_files = [];
    }
    if ((callback == null) && typeof config_files === 'function') {
      callback = config_files;
      config_files = [];
    }
    _ref = process.argv;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      arg = _ref[_i];
      if (arg.substr(0, 9) === '--config=' && arg.length > 9) {
        config_files.push(arg.substr(9));
      }
    }
    if (typeof config_files === 'string') {
      config_files = [config_files];
    }
    if (!config_files.length) {
      config_files.push('config.ini');
    }
    next = function(err) {
      if (err) {
        if (typeof callback === 'function') {
          return callback(err);
        }
        return;
      }
      if (config_files.length) {
        return file_load(module.exports, config_files.shift(), next);
      }
      if (module.exports.load === removable_loader) {
        delete module.exports.load;
      }
      if (typeof callback === 'function') {
        return callback();
      }
    };
    return next();
  };

}).call(this);
